apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - image: bitnami/mysql
    env: 
    - name: 
      valueFrom: 
        secretKeyRef: 
          name: mysql
          key: password
    imagePullPolicy: IfNotPresent
    name: mysql
  restartPolicy: Always