apiVersion: v1
kind: Service
metadata:
  name: frontend-beta
  labels:
    beta: guestbook
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    beta: guestbook